FROM ubuntu:22.04
RUN apt-get update && apt-get install -y \
    build-essential \
    iputils-ping \
    libsqlite3-dev
WORKDIR /app
COPY . .
RUN g++ -o main *.cpp *.h -pthread -lsqlite3
CMD ["./main"]